name: smallstuff
favicon: null
layout_spectrum: 0.74754
typography_spectrum: 0.60848
title: smallstuff from the internex
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2a0505'
    - '#7b2828'
    - '#aa4f4f'
    - '#4c1818'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
