name: smallstuff
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6970948080997914
title: smallstuff
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2a0505'
    - '#7b2828'
    - '#aa4f4f'
    - '#4c1818'
  brandStrength: 0.5625
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
